/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxDemo: typeof import('./.vitepress/vitepress/components/CheckboxDemo.vue')['default']
    DemoBlock: typeof import('./.vitepress/vitepress/components/DemoBlock.vue')['default']
    DemoBox: typeof import('./.vitepress/vitepress/components/DemoBox.vue')['default']
    DemoPlayground: typeof import('./.vitepress/vitepress/components/DemoPlayground.vue')['default']
    DialogBasicDemo: typeof import('./.vitepress/vitepress/components/DialogBasicDemo.vue')['default']
    DialogCenterDemo: typeof import('./.vitepress/vitepress/components/DialogCenterDemo.vue')['default']
    DialogDemo: typeof import('./.vitepress/vitepress/components/DialogDemo.vue')['default']
    DialogFormDemo: typeof import('./.vitepress/vitepress/components/DialogFormDemo.vue')['default']
    DialogFullscreenDemo: typeof import('./.vitepress/vitepress/components/DialogFullscreenDemo.vue')['default']
    DialogHeaderDemo: typeof import('./.vitepress/vitepress/components/DialogHeaderDemo.vue')['default']
    Home: typeof import('./.vitepress/vitepress/components/Home.vue')['default']
    IconDemo: typeof import('./.vitepress/vitepress/components/IconDemo.vue')['default']
    JffDemoContainer: typeof import('./.vitepress/vitepress/components/JffDemoContainer.vue')['default']
    Layout: typeof import('./.vitepress/vitepress/components/Layout.vue')['default']
    MessageDemo: typeof import('./.vitepress/vitepress/components/MessageDemo.vue')['default']
    NotFound: typeof import('./.vitepress/vitepress/components/NotFound.vue')['default']
    Page: typeof import('./.vitepress/vitepress/components/Page.vue')['default']
    RadioDemo: typeof import('./.vitepress/vitepress/components/RadioDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchDemo: typeof import('./.vitepress/vitepress/components/SwitchDemo.vue')['default']
  }
}

// For TSX support
declare global {
  const CheckboxDemo: typeof import('./.vitepress/vitepress/components/CheckboxDemo.vue')['default']
  const DemoBlock: typeof import('./.vitepress/vitepress/components/DemoBlock.vue')['default']
  const DemoBox: typeof import('./.vitepress/vitepress/components/DemoBox.vue')['default']
  const DemoPlayground: typeof import('./.vitepress/vitepress/components/DemoPlayground.vue')['default']
  const DialogBasicDemo: typeof import('./.vitepress/vitepress/components/DialogBasicDemo.vue')['default']
  const DialogCenterDemo: typeof import('./.vitepress/vitepress/components/DialogCenterDemo.vue')['default']
  const DialogDemo: typeof import('./.vitepress/vitepress/components/DialogDemo.vue')['default']
  const DialogFormDemo: typeof import('./.vitepress/vitepress/components/DialogFormDemo.vue')['default']
  const DialogFullscreenDemo: typeof import('./.vitepress/vitepress/components/DialogFullscreenDemo.vue')['default']
  const DialogHeaderDemo: typeof import('./.vitepress/vitepress/components/DialogHeaderDemo.vue')['default']
  const Home: typeof import('./.vitepress/vitepress/components/Home.vue')['default']
  const IconDemo: typeof import('./.vitepress/vitepress/components/IconDemo.vue')['default']
  const JffDemoContainer: typeof import('./.vitepress/vitepress/components/JffDemoContainer.vue')['default']
  const Layout: typeof import('./.vitepress/vitepress/components/Layout.vue')['default']
  const MessageDemo: typeof import('./.vitepress/vitepress/components/MessageDemo.vue')['default']
  const NotFound: typeof import('./.vitepress/vitepress/components/NotFound.vue')['default']
  const Page: typeof import('./.vitepress/vitepress/components/Page.vue')['default']
  const RadioDemo: typeof import('./.vitepress/vitepress/components/RadioDemo.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SwitchDemo: typeof import('./.vitepress/vitepress/components/SwitchDemo.vue')['default']
}