/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Home: typeof import('./.vitepress/vitepress/components/Home.vue')['default']
    Layout: typeof import('./.vitepress/vitepress/components/Layout.vue')['default']
    NotFound: typeof import('./.vitepress/vitepress/components/NotFound.vue')['default']
    Page: typeof import('./.vitepress/vitepress/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
