/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxDemo: typeof import('./.vitepress/vitepress/components/CheckboxDemo.vue')['default']
    DemoBlock: typeof import('./.vitepress/vitepress/components/DemoBlock.vue')['default']
    DemoBox: typeof import('./.vitepress/vitepress/components/DemoBox.vue')['default']
    DemoPlayground: typeof import('./.vitepress/vitepress/components/DemoPlayground.vue')['default']
    DialogBasicDemo: typeof import('./.vitepress/vitepress/components/DialogBasicDemo.vue')['default']
    DialogCenterDemo: typeof import('./.vitepress/vitepress/components/DialogCenterDemo.vue')['default']
    DialogDemo: typeof import('./.vitepress/vitepress/components/DialogDemo.vue')['default']
    DialogFormDemo: typeof import('./.vitepress/vitepress/components/DialogFormDemo.vue')['default']
    DialogFullscreenDemo: typeof import('./.vitepress/vitepress/components/DialogFullscreenDemo.vue')['default']
    DialogHeaderDemo: typeof import('./.vitepress/vitepress/components/DialogHeaderDemo.vue')['default']
    Home: typeof import('./.vitepress/vitepress/components/Home.vue')['default']
    IconDemo: typeof import('./.vitepress/vitepress/components/IconDemo.vue')['default']
    JffButton: typeof import('@justforfun-ui/components')['JffButton']
    JffCheckbox: typeof import('@justforfun-ui/components')['JffCheckbox']
    JffCheckboxGroup: typeof import('@justforfun-ui/components')['JffCheckboxGroup']
    JffDemoContainer: typeof import('./.vitepress/vitepress/components/JffDemoContainer.vue')['default']
    JffDialog: typeof import('@justforfun-ui/components')['JffDialog']
    JffForm: typeof import('@justforfun-ui/components')['JffForm']
    JffFormItem: typeof import('@justforfun-ui/components')['JffFormItem']
    JffIcon: typeof import('@justforfun-ui/components')['JffIcon']
    JffInput: typeof import('@justforfun-ui/components')['JffInput']
    JffOption: typeof import('@justforfun-ui/components')['JffOption']
    JffRadio: typeof import('@justforfun-ui/components')['JffRadio']
    JffRadioGroup: typeof import('@justforfun-ui/components')['JffRadioGroup']
    JffSelect: typeof import('@justforfun-ui/components')['JffSelect']
    JffSwitch: typeof import('@justforfun-ui/components')['JffSwitch']
    Layout: typeof import('./.vitepress/vitepress/components/Layout.vue')['default']
    MessageDemo: typeof import('./.vitepress/vitepress/components/MessageDemo.vue')['default']
    NotFound: typeof import('./.vitepress/vitepress/components/NotFound.vue')['default']
    Page: typeof import('./.vitepress/vitepress/components/Page.vue')['default']
    RadioDemo: typeof import('./.vitepress/vitepress/components/RadioDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchDemo: typeof import('./.vitepress/vitepress/components/SwitchDemo.vue')['default']
  }
}

// For TSX support
declare global {
  const CheckboxDemo: typeof import('./.vitepress/vitepress/components/CheckboxDemo.vue')['default']
  const DemoBlock: typeof import('./.vitepress/vitepress/components/DemoBlock.vue')['default']
  const DemoBox: typeof import('./.vitepress/vitepress/components/DemoBox.vue')['default']
  const DemoPlayground: typeof import('./.vitepress/vitepress/components/DemoPlayground.vue')['default']
  const DialogBasicDemo: typeof import('./.vitepress/vitepress/components/DialogBasicDemo.vue')['default']
  const DialogCenterDemo: typeof import('./.vitepress/vitepress/components/DialogCenterDemo.vue')['default']
  const DialogDemo: typeof import('./.vitepress/vitepress/components/DialogDemo.vue')['default']
  const DialogFormDemo: typeof import('./.vitepress/vitepress/components/DialogFormDemo.vue')['default']
  const DialogFullscreenDemo: typeof import('./.vitepress/vitepress/components/DialogFullscreenDemo.vue')['default']
  const DialogHeaderDemo: typeof import('./.vitepress/vitepress/components/DialogHeaderDemo.vue')['default']
  const Home: typeof import('./.vitepress/vitepress/components/Home.vue')['default']
  const IconDemo: typeof import('./.vitepress/vitepress/components/IconDemo.vue')['default']
  const JffButton: typeof import('@justforfun-ui/components')['JffButton']
  const JffCheckbox: typeof import('@justforfun-ui/components')['JffCheckbox']
  const JffCheckboxGroup: typeof import('@justforfun-ui/components')['JffCheckboxGroup']
  const JffDemoContainer: typeof import('./.vitepress/vitepress/components/JffDemoContainer.vue')['default']
  const JffDialog: typeof import('@justforfun-ui/components')['JffDialog']
  const JffForm: typeof import('@justforfun-ui/components')['JffForm']
  const JffFormItem: typeof import('@justforfun-ui/components')['JffFormItem']
  const JffIcon: typeof import('@justforfun-ui/components')['JffIcon']
  const JffInput: typeof import('@justforfun-ui/components')['JffInput']
  const JffOption: typeof import('@justforfun-ui/components')['JffOption']
  const JffRadio: typeof import('@justforfun-ui/components')['JffRadio']
  const JffRadioGroup: typeof import('@justforfun-ui/components')['JffRadioGroup']
  const JffSelect: typeof import('@justforfun-ui/components')['JffSelect']
  const JffSwitch: typeof import('@justforfun-ui/components')['JffSwitch']
  const Layout: typeof import('./.vitepress/vitepress/components/Layout.vue')['default']
  const MessageDemo: typeof import('./.vitepress/vitepress/components/MessageDemo.vue')['default']
  const NotFound: typeof import('./.vitepress/vitepress/components/NotFound.vue')['default']
  const Page: typeof import('./.vitepress/vitepress/components/Page.vue')['default']
  const RadioDemo: typeof import('./.vitepress/vitepress/components/RadioDemo.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SwitchDemo: typeof import('./.vitepress/vitepress/components/SwitchDemo.vue')['default']
}